server:
  port: 8081

spring.cloud.stream:
  kafka:
    binder:
      brokers: :BrokerID
      defaultBrokerPort: 9092
  bindings:
    input:
      destination: mytopic
      group: mygroup
    output:
      destination: mytopic
